### ISSUE TITLE
Long exception if file doesn't exist

### ISSUE THREAD

**Issue by tbm** [jord1e/jbeancount#4]
If you call jbeancount with a file that doesn't exist, you get a long exception - it would be nice to get a proper error message.

```
./jbeancount check xxx
java.util.concurrent.CompletionException: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: ./xxx
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1177)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at nl.jrdie.beancount.Beancount.createJournal(Beancount.java:51)
	at nl.jrdie.beancount.Beancount.createJournal(Beancount.java:31)
	at nl.jrdie.beancount.Beancount.createJournalSync(Beancount.java:27)
	at nl.jrdie.beancount.cli.commands.CheckJournal.call(CheckJournal.java:19)
	at nl.jrdie.beancount.cli.commands.CheckJournal.call(CheckJournal.java:10)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at nl.jrdie.beancount.cli.BeancountCli.main(BeancountCli.java:39)
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: ./xxx
	at nl.jrdie.beancount.parser.BeancountParser.parseJournalImpl(BeancountParser.java:39)
	at nl.jrdie.beancount.parser.BeancountParser.parseJournal(BeancountParser.java:24)
	at nl.jrdie.beancount.Beancount.lambda$createJournal$0(Beancount.java:47)
	at nl.jrdie.beancount.construe.SyncConstrueStrategy.construe(SyncConstrueStrategy.java:11)
	at nl.jrdie.beancount.Beancount.createJournal(Beancount.java:47)
	... 13 more
Caused by: java.nio.file.NoSuchFileException: ./xxx
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1851)
	at java.nio.file.Files.size(Files.java:2468)
	at org.antlr.v4.runtime.CharStreams.fromPath(CharStreams.java:86)
	at org.antlr.v4.runtime.CharStreams.fromPath(CharStreams.java:76)
	at nl.jrdie.beancount.parser.BeancountParser.parseJournalImpl(BeancountParser.java:37)
	... 17 more
```

**Comment by jord1e** [comment]
Fixed in https://github.com/jord1e/jbeancount/commit/31bad8873acbfbab7ce0fd2fe5636e0982cfdda0 (also works for includes)

![grafik](https://user-images.githubusercontent.com/30464310/181835420-f360b04c-b9e4-4b3e-a86c-ab4e79c12a87.png)


Also made parsing/lexer error messages a little bit better - will improve them even more down the line. Currently I just get them directly from ANTLR. Still some work to do

![grafik](https://user-images.githubusercontent.com/30464310/181835310-b50b7399-3341-4670-9ce3-c9b1b0eba80f.png)

![grafik](https://user-images.githubusercontent.com/30464310/181835357-112afbb3-1548-4000-bb05-81cacb73c862.png)
