### ISSUE TITLE
Doesn't allow quoted quotation mark in narration

### ISSUE THREAD

**Issue by tbm** [jord1e/jbeancount#7]
This is valid in beancount:

```
2010-01-01 open Expenses:Entertainment
2010-01-01 open Assets:Voucher:Amazon

2022-03-27 * "Amazon.com" "Book \"Dagboek van 'n dork 2\""
  Expenses:Entertainment                                    9.35 USD
  Assets:Voucher:Amazon                                    -9.35 USD
```

but:

```
line 4:35 token recognition error at: 'agboek '
line 4:42 token recognition error at: 'van '
line 4:46 token recognition error at: '''
line 4:47 token recognition error at: 'n '
line 4:49 token recognition error at: 'dork '
line 4:55 token recognition error at: '\'
line 4:34 no viable alternative at input '2022-03-27*"Amazon.com""Book \"D'
line 4:58 mismatched input 'indent' expecting {<EOF>, 'include', 'pushtag', 'poptag', 'option', 'plugin', DATE, COMMENT, EOL}
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1177)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at nl.jrdie.beancount.Beancount.createJournal(Beancount.java:51)
	at nl.jrdie.beancount.Beancount.createJournal(Beancount.java:31)
	at nl.jrdie.beancount.Beancount.createJournalSync(Beancount.java:27)
	at nl.jrdie.beancount.cli.commands.CheckJournal.call(CheckJournal.java:19)
	at nl.jrdie.beancount.cli.commands.CheckJournal.call(CheckJournal.java:10)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at nl.jrdie.beancount.cli.BeancountCli.main(BeancountCli.java:39)
Caused by: java.lang.NullPointerException
	at nl.jrdie.beancount.parser.BeancountAntlrToLanguage.createTransactionDirective(BeancountAntlrToLanguage.java:185)
	at nl.jrdie.beancount.parser.BeancountAntlrToLanguage.createDirective(BeancountAntlrToLanguage.java:139)
	at nl.jrdie.beancount.parser.BeancountAntlrToLanguage.createDeclaration(BeancountAntlrToLanguage.java:117)
	at nl.jrdie.beancount.util.ImmutableKit.map(ImmutableKit.java:22)
	at nl.jrdie.beancount.parser.BeancountAntlrToLanguage.createDeclarations(BeancountAntlrToLanguage.java:110)
	at nl.jrdie.beancount.parser.BeancountAntlrToLanguage.createJournal(BeancountAntlrToLanguage.java:103)
	at nl.jrdie.beancount.parser.BeancountParser.parseJournalImpl(BeancountParser.java:65)
	at nl.jrdie.beancount.parser.BeancountParser.parseJournal(BeancountParser.java:24)
	at nl.jrdie.beancount.Beancount.lambda$createJournal$0(Beancount.java:47)
	at nl.jrdie.beancount.construe.SyncConstrueStrategy.construe(SyncConstrueStrategy.java:11)
	at nl.jrdie.beancount.Beancount.createJournal(Beancount.java:47)
	... 13 more
```

**Comment by jord1e** [comment]
Fixed in https://github.com/jord1e/jbeancount/commit/0690ccecbe19ccccf0702ca292f5acc4d76f910f
