### ISSUE TITLE
Doesn't accept thousand separator , (1,000 or 1,000,000)

### ISSUE THREAD

**Issue by tbm** [jord1e/jbeancount#9]
This is valid beancount:

```
1970-01-01 open Assets:Test
1970-01-01 open Equity:Opening-Balance

2018-03-26 * "Thousand"
  Assets:Test                   1,000 EUR
  Equity:Opening-Balance

2018-03-26 * "Thousand"
  Assets:Test                1,000.00 EUR
  Equity:Opening-Balance

2018-03-26 * "Million"
  Assets:Test            1,000,000.00 EUR
  Equity:Opening-Balance
```
but:

```
java.util.concurrent.CompletionException: java.lang.NumberFormatException: Character , is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1177)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at nl.jrdie.beancount.Beancount.createJournal(Beancount.java:51)
	at nl.jrdie.beancount.Beancount.createJournal(Beancount.java:31)
	at nl.jrdie.beancount.Beancount.createJournalSync(Beancount.java:27)
	at nl.jrdie.beancount.cli.commands.CheckJournal.call(CheckJournal.java:19)
	at nl.jrdie.beancount.cli.commands.CheckJournal.call(CheckJournal.java:10)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at nl.jrdie.beancount.cli.BeancountCli.main(BeancountCli.java:39)
```

**Comment by jord1e** [comment]
Fixed in https://github.com/jord1e/jbeancount/commit/e92ab9f22d9488a102aa6e38e8e13d85cf44dc89
